---
title: "R Prescribed Inhalers"
output: html_notebook
---
```{r}
require("janitor")
require("data.table")
require("tidyverse")
require("httr")
require("jsonlite")
require("rlist")
require("reshape")
library(readxl)
library(janitor)
library(foreach)
library(tidylog)
library(ggplot2)
library(ggrepel)
library(httr)
library(jsonlite)
library(rlist)
library(tidyverse)
library(foreach)
library(reshape)



```


```{R}


# mainDir <- getwd()
# subDir <- "InhalersOuput"


#Load carbon per inhaler
Inhaler <- read.csv("C:/Users/kev/Documents/GitHub/Inhalers-Carbon-Content/Inhalers.csv")
Inhalers <- na.omit(Inhaler)
Inhalers <- subset(Inhalers, Carbon.per.device>0)
#View(Inhalers)

  # if (file.exists(subDir)){
  #     setwd(file.path(mainDir, subDir))
  #     } else {
  #     dir.create(file.path(mainDir, subDir))
  #     setwd(file.path(mainDir, subDir))
  # 
  # }  


rm(df)
df <- c("items","quantity","actual_cost","date","row_id","row_name","ccg","setting","Org","drugCode","drug","carbon")
names(df)<-c("items","quantity","actual_cost","date","row_id","row_name","ccg","setting","Org","drugCode","drug","carbon")

request <- function(drugCode,orgCode,Drugname,CarbonPI) {
  # print(drugCode)
   orgCode="36J"
    #drugCode="0302000N0AAACAC"
   
   RequestString <- paste0("https://openprescribing.net/api/1.0/spending_by_practice/?code=",drugCode,"&org=",orgCode,"&format=json")
#   
#   
   response <- GET(RequestString)
   contains <- content(response, as = "text", encoding = "UTF-8")
   
   newdf <- fromJSON(contains, flatten = TRUE) %>% data.frame()
   
   if (nrow(newdf)== 0)
   {return()}
   
   newdf$Org <- orgCode
   newdf$drugCode <-drugCode
   newdf$drug <- Drugname 
   newdf$carbon <- CarbonPI
   write.table(newdf, 'output1.Rdata', sep = ",", col.names = !file.exists("output1.Rdata"), append = TRUE, row.names = FALSE)
   return()
}

i <- 1
j = NROW(Inhalers)
while (i < j)
  {RequestID = as.character(Inhalers[i,]$id)
  
  request(RequestID,"36J",Inhalers[i,]$name,Inhalers[i,]$Carbon.per.device)
  i = i+1
  }

```

```{r}

```






```{r}

#From here chunks only graph the prepared data above.

#Add total carbon and keep only last 12 months
DataFrame <- read.csv("C:/Users/kev/Documents/GitHub/Inhalers-Carbon-Content/output1.Rdata", stringsAsFactors=FALSE)


DataFrame$TotalCarbon = DataFrame$items * DataFrame$carbon

MonthsAgo12 <- as.POSIXlt(max(DataFrame$date))

MonthsAgo12$year <- MonthsAgo12$year - 1
MonthsAgo12 <- as.Date(MonthsAgo12)
Last12months <- subset(DataFrame, date > MonthsAgo12 )

total_per_GP_Practice <- tapply(Last12months$TotalCarbon,Last12months$row_name,sum)
total_per_inhaler_type <- tapply(Last12months$TotalCarbon,Last12months$drug,sum)

Pivot <- Last12months %>%
  group_by(row_name, drug) %>%
  summarize(total_carbon_for_device_and_Surgery = sum(TotalCarbon))

pivot_table <- cast(Pivot, row_name ~ drug)
write.csv(pivot_table,"Pivot.csv")
CCG_df<-Last12months%>% 
        group_by(row_name)%>%
        summarise(Total_Quan = sum(TotalCarbon) )
CCG_df <- subset(CCG_df,Total_Quan>5000)
ggplot(data = CCG_df,mapping=aes(x=Total_Quan , y=row_name)) +geom_col()



```


```{r}
Epracur <- read_csv("Epracur.csv", col_names = FALSE, na = "empty")

postcode <- merge(Last12months, Epracur, by.x ="row_id", by.y ="X1")
postcode <- merge(postcode, Inhalers, by.x = "drugCode", by.y = "id")
Pivot <- postcode %>%
  group_by(row_name, Category) %>%
  summarize(total_device_and_Surgery = sum(quantity))

pivot_table <- cast(Pivot, row_name ~ Category)
write.csv(pivot_table,"Pivot1.csv")
```